### ISSUE TITLE
Button style conflict when using Suki and Cheryl

### ISSUE THREAD

**Issue by fulco813** [kikipoulet/CherylUI#6]
Hi, I'm writing an Avalonia demo project, and I want to mainly use Suki controls, when it comes to Android and IOS, I want to use Bottom Tabs in Cheryl. So I install both, and my app window(running on Windows10) become like this👇
![微信截图_20240529165138](https://github.com/kikipoulet/CherylUI/assets/67252536/aea4b16d-b98e-49c5-b41b-a9c28417b184)

**Comment by kikipoulet** [comment]
Hi,

I would advise you to not use both in the same project, there are probably some named use that are the same. If you really want to do so, maybe check that Cheryl is included before Suki, so Suki values overrides it if necessary.

For cross-platform development, I would advice you to make three seperate project.
- A Class Library project for all your backend
- A desktop avalonia app for your desktop development, using SukiUI and your backend
- A xplat Avalonia app for Android/IOS, using CherylUI and your backend

To me, the benefit of cross-platform is not to be able to make one view for all the platforms, it's almost impossible to do it correctly, but to be able to use the same stack for everything. If you want to do a nice desktop UI and a nice Mobile UI, sharing the same view is impossible to me, no matter the framework btw. 

Hope it helps you 👍

**Comment by fulco813** [comment]
Thanks for your advice, that's helpful！
Now I'm working on seperating core library from my original project.
